@startuml
actor User
participant "Приложение" as App
participant "Сервер" as Server

User -> App : Заходит в телеграмм-бота
User -> App : Загружает фотографию достопримечательности
App -> Server : Загружает картинку
Server -> App : Возвращает информацию о достопримечательности

User -> App : Ставит оценку достопримечатльности
App -> Server : Обновляет рейтинг
User -> App : Запрашивает рейтинг достопримечальностей
App -> Server : Запрос рейтинга
Server -> App : Возвращает рейтинг достопримечальностей

User -> App : Вводит телеграмм-ник пользователя
User -> App : Добавляет в "Друзья"
App -> Server : Обновляет список "Друзей" пользователя

User -> App : Выбирает достопримечательность из списка
User -> App : Выбирает пользователя из "Друзей"
User -> App : Нажимает "Поделиться с другом"
App -> Server : Запрашивает отправку сообщения
Server -> App : Отправляет другу пользователя сообщение с предложенной достопримечательностью

User -> App : Подключает уведомления о мероприятиях в Москве
App -> Server : Запрашивает отправку уведомлений о мероприятиях в Москве
Server -> App : Отправляет уведомления всем подключенным пользователям

@enduml