spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log=classpath:db/changelog/db:
      changelog-master:
        yaml:
